"""Initial tables.

Revision ID: bdd7ae0e0eb7
Revises:
Create Date: 2024-07-07 14:55:44.169099

"""  # noqa: INP001
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "bdd7ae0e0eb7"
down_revision: Union[str, None] = None  # noqa: FA100
branch_labels: Union[str, Sequence[str], None] = None  # noqa: FA100
depends_on: Union[str, Sequence[str], None] = None  # noqa: FA100


def upgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
