"""initial.

Revision ID: dbe2cb688f14
Revises:
Create Date: 2024-06-12 15:21:48.524163

"""  # noqa: INP001
from typing import Sequence, Union

#import sqlalchemy as sa  # noqa: ERA001

#from alembic import op  # noqa: ERA001

# revision identifiers, used by Alembic.
revision: str = "dbe2cb688f14"
down_revision: Union[str, None] = None  # noqa: FA100
branch_labels: Union[str, Sequence[str], None] = None  # noqa: FA100
depends_on: Union[str, Sequence[str], None] = None  # noqa: FA100


def upgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
