name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify your Python version
          cache: poetry
      
      - name: Install Python dependencies
        run: poetry install

      - name: Set up environment variables
        env:
          MY_SECRET_KEY: ${{ secrets.KEY_DB }}
        run: |
          echo "Using secret: $MY_SECRET_KEY"
      


